version: '3.8'

services:
  db:
    image: 'postgres:latest'
    volumes:
      - 'databse:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password

  web:
    build: .
    depends_on:
      - 'db'
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    volumes:
      - .:/app

volumes:
  databse: